# Generated by Django 3.2.5 on 2021-07-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
