# Generated by Django 3.2.5 on 2021-07-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_newuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='pwd',
            field=models.IntegerField(default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newuser',
            name='role',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
