# Generated by Django 2.2.12 on 2021-07-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='username',
        ),
    ]
