# Generated by Django 3.2.5 on 2021-07-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignments_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
