# Generated by Django 3.2.5 on 2021-07-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=20),
        ),
    ]
