# Generated by Django 3.2.5 on 2021-07-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackform', '0003_auto_20210710_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='session',
            new_name='insightful_session',
        ),
    ]
