# Generated by Django 3.2.5 on 2021-07-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackform', '0004_rename_session_feedback_insightful_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='question1',
            new_name='name_one_animal',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='rating',
            new_name='rate_the_session',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='insightful_session',
            new_name='was_the_session_insightful',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='question2',
            new_name='what_is_this',
        ),
    ]
