# Generated by Django 4.0.dev20210430120422 on 2021-07-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_alter_link_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=500)),
                ('meeting_link', models.URLField(max_length=2000)),
            ],
        ),
    ]
