# Generated by Django 4.0.dev20210430120422 on 2021-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_addlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlink',
            name='end_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='addlink',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addlink',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addlink',
            name='start_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='addlink',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addlink',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addlink',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
