# Generated by Django 3.2.5 on 2021-07-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_addlink_end_time_addlink_friday_addlink_monday_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddLink',
        ),
    ]
