# Generated by Django 3.2.5 on 2021-07-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
