# Generated by Django 3.2.5 on 2021-07-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_alter_tasks_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
